AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create S3 bucket for a website hosting

Parameters:
  BUCKETNAME:
    Description: Name of a bucket to host a website
    Type: String

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BUCKETNAME
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
    DeletionPolicy: Retain
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'WebsiteBucket'
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join [ '', [ 'arn:aws:s3:::', !Ref 'WebsiteBucket', /* ] ]